# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
puts "🌱 Seeding spices..."

#Recipe

hawaiian_Island_Fried_Rice = Recipe.create(name: "Hawaiian Island fried Rice", image: "https://savoryspicerack.com/wp-content/uploads/DSC_0288.jpg", description: "Essentially, fried rice made with whatever leftovers you have in your fridge. Traditionally, proteins made with this would be Spam, Portuguese sausage, and char siu.", instruction:["Heat a wok or large frying pan over medium heat. Drizzle in 2 tablespoons of oil and scramble the eggs for 30 seconds or until cooked to your preference. Set the eggs aside on a plate.","Drizzle in 2 tablespoons of oil again to the wok. Fry the toughest vegetable (for this recipe it is the carrots) for a couple of minutes. Then keep frying the next tender vegetable (onions) and fry for another couple of minutes. Lastly, add in the most tender vegetable and cook for a minute. Set aside the cooked vegetables.","If your meat isn't cooked or you would like to warm it up, fry the meat in the wok for a few minutes or until the meat is cooked","Drizzle in 2 tablespoons of oil again to the wok. Add in the leftover rice and fry it until all of the rice has been coated in the oil. Add in the oyster sauce, shoyu, white pepper, and salt. Stir fry until well combined.","Add everything back to the wok. Eggs, vegetables, and meat. Stir fry everything until has mixed well. Serve hot as a hearty meal or side dish. Enjoy!"],cooking_time: "25 min", servings: 7, cuisine: "Hawaiian")
mochiko_Chicken = Recipe.create(name:"Mochiko Chicken", image:"https://www.tasteofhome.com/wp-content/uploads/2020/10/Mochiko-Chicken-HF.jpg?resize=768,768",description: "Mochiko chicken is Hawaii's version of popcorn chicken. Bite-size pieces of chicken marinated in a mochiko flour mixture and deep-fried.",instruction:["Create the marinade by combining mochiko, cornstarch, sugar, soy sauce, eggs and green onions in a medium bowl. Make sure everything is blended. Cut chicken into bite-size pieces like nuggets, getting them as close to uniform in size as possible so they'll cook evenly when deep-frying.","Add chicken to the marinade and use your hands to massage the chicken pieces and make sure they're all coated by the marinade. Cover and refrigerate for at least 6 hours or up to overnight.","Bring oil to 350 degrees F in a deep-fryer or Dutch oven.","Fry chicken in batches until crispy, about 10 minutes. Sprinkle sesame seeds over the top, if using, and serve."],cooking_time:"6 hrs 35 mins",servings: 6, cuisine:"Hawaiian")
haupia = Recipe.create(name: "Haupia",image:"https://www.favfamilyrecipes.com/wp-content/uploads/2020/07/Haupia-recipe-vertical-375x288.jpg",description: "Haupia is a classic Hawaiian dessert that's like a cross between coconut pudding and jelly.Lightly sweet and made primarily from coconut milk, haupia is served chilled and cut into squares, and it's like little refreshing bites of Hawaii!", instruction:["Combine cornstarch and water in a small bowl. Stir until cornstarch is dissolved then set aside.","In a medium-sized sauce pan over medium heat, combine coconut milk and sugar.","Whisk constantly until mixture begins to simmer.","While continuing to whisk, SLOWLY pour in the water/cornstarch mixture until it thickens."], cooking_time: "2 hrs 15 mins", servings: 16, cuisine: "Hawaiian")
rourou = Recipe.create(name: "Rourou", image:"http://thegentlemansplate.com/wp-content/uploads/2016/06/Fijian-Roro-Hero.jpg",description: "Rourou is a traditional Fijian dish prepared from taro leaves stewed in coconut milk. The simple Rourou is usually served either as a soup or a side dish in balls form accompanying various fish or chicken dishes and boiled cassava.", instruction:["Remove the frozen chopped spinach out of the wrapper, and place on a microwave safe plate and heat for 1½ minutes on high in your microwave oven, until it has mostly thawed.","In a medium sauce pan, bring one cup of water to a boil; add in the chopped onion, garlic paste, chilis, and salt and simmer with the lid closed until tender (about 4 minutes).","Add the spinach to the pot, adding more water if needed (it should be just covering the spinach). Let the spinach cook for an additional 4-5 minutes, until everything is tender.","Reduce the heat to medium and add the entire can of coconut milk and stir. Let this boil for an additional 4-5 minutes, until the milk thickens and absorbs all of the flavor.","Add an additional cup of water at this stage, to prevent the coconut milk from burning; boil until you reach a desired consistency (similar to a Thai curry).","Season with the juice of half a lime, adding more lime and salt per your taste.",], cooking_time: "35 mins", servings: 2, cuisine: "Fijian")
kokoda = Recipe.create(name: "Kokoda", image: "https://foreignfork.com/wp-content/uploads/2021/04/kokoda-8-768x1152.jpg",description: "Kokoda is a form of Fish Cevice that is served with coconut milk in order to balance out the acidity of the lime juice.", instruction:["Cut the Mahi Mahi into cubed, bite-sized pieces. Place the pieces in a bowl and then cover them with the squeezed lime juice. Cover and place in the fridge for about 6 hours.","You will know the fish is cooked when the skin has turned white and opaque. You can cut into one of the pieces of fish to make sure that it is this color all the way through!","When the fish is cooked, add the coconut milk and the diced vegetables. Stir, then season with salt and pepper to taste.","Spoon into bowls or coconut halves. Enjoy!"],cooking_time:"6 hrs 20 mins ", servings: 4, cuisine:"Fijian",)
purini = Recipe.create(name: "Purini", image:"https://i1.wp.com/pacificislandrecipe.com/wp-content/uploads/2017/02/purini-in-custard.jpg",description: "This is a Typical Fijian dessert the main elements include cassava starch, brown sugar and coconut cream.", instruction:["Melt sugar in a small saucepan on medium heat, taking care not to burn the sugar.","Slowly add coconut cream to the melted sugar, one tablespoon at a time, stirring it in well after each addition.","Stirring constantly, bring the syrup to the boil then remove from the heat and allow to cool.","Combine dry ingredients in a large bowl and whisk ingredients together.","Fold the sugar syrup into the dry ingredients and mix well.","Pour the batter into a buttered 2 litre pudding tin and steam for 1½ hours in a large pot over the stovetop.","Test if fully cooked with a skewer inserted into the middle of pudding and return to stovetop if necessary."],cooking_time: "1 hrs 30 mins", servings: 10, cuisine:"Fijian" )
fungi = Recipe.create(name: "Fungi and Saltfish", image: "http://www.wadadlistyle.com/wp-content/uploads/2019/04/Screenshot-2019-04-26-13.02.16.png", description: "Antiguan fungie is created using cornmeal and okra paste which are shaped into balls and then cooked together. Saltfish is usually cooked and served as a side dish along with another traditional Antiguan dish, Chop-up.", instruction:["Place water, okra and salt in a pan. Bring to boil until okras are cooked. Remove half the liquid. Stir with a wooden spoon. The corn meal is mixed to a pasty batter by adding cold water then stirring & mixing this.","Add wet corn meal. Reduce the heat, stir continuously with a wooden spoon until mixture becomes fairly stiff.","When the mixture breaks away cleanly from the pan (i.e it does not stick), the fungee is ready. Butter a bowl, turn the mixture into the bowl, shaking it into the shape of the bowl, then turn it out into a serving dish."], cooking_time:" 1 hr 20 mins", servings: 4, cuisine: "Antiguan, Caribbean")
duncana = Recipe.create(name: "Duncana", image:"https://foreignfork.com/wp-content/uploads/2018/10/7585691552_IMG_8375.jpg",description: "Duncanc are dumplings made with sweeet potato, coconut and cinnamon. Form the mixture into a dumplings,wrap in a banana leaves and secure with twine and then boil.", instruction:["Wash banana leaves and remove central stems.","Bring a large pot of water to boil. Add leaves and blanch for about 10 seconds to soften. Remove and run under water to cool. Set aside.","Combine all remaining ingredients, mixing to make a very soft dough. Add a little extra water if dough is too stiff, or add flour if dough is too liquid.","Place about ½ cup dough on each leaf. Fold to make a neat parcel. Secure by tying with kitchen twine or leftover strips of banana leaf. Dough can also be wrapped in aluminum foil if banana leaves are unavailable.","Bring a large pot of water to a boil. Add ducuna packets and simmer for about 45 minutes. Drain and allow to cool.","Serve warm or at room temperature."], cooking_time: "1 hr 5mins ", servings: 10, cuisine: "Antiguan")
black_Pineapple = Recipe.create(name:"Pineapple Salad with Sweet Rum Drizzle", image:"https://www.internationalcuisine.com/wp-content/uploads/2014/05/Antigua-pineapple-salad-1024x685.jpg",description: "Antigua is known for its very sweet and juicy black pineapple. The simple salad incorporates just a honey and rum drizzle that adds a great flavor to the pineapple; serve them in boats for a pleasant tropical feel.",instruction:["Cut the pineapple in ½ the long way and then into quarters.","Cut out the core and cut the pineapple into chucks, reserving the shell for serving.","In a bowl, Whisk together the honey and dark rum","Add in pineapple pieces and coat well.","Spoon the coated pineapple pieces into the shells and serve",],cooking_time: "10 mins", cuisine: "Antiguan")
lawar = Recipe.create(name:"Lawar", image:"https://img.theculturetrip.com/1440x/smart/wp-content/uploads/2021/07/kkc71c.jpg",description: "Lawar is made by mixing chopped meat with various green vegetables and grated coconut. As for the meat, the choices are beef, chicken, duck, pork, turtle, or a combination of those.", instruction:["Bring a medium pot of water to a boil. Add the mung bean sprouts into the boiling water and turn off the heat. Let them sit in the boiling water for about 3 minutes. Discard the water and refresh the bean sprouts with cold water. Set aside","Put everything for ground ingredients in a blender and process into a paste. Set aside","You can finely mince the chicken meat. Use about 1 Tbsp of cooking oil and stir fry the meat until they are cooked through, remove from the pan and set aside","Add another one tablespoon of oil and stir fry the ground ingredients until really fragrant, about 3-4 minutes. Add the finely chopped beans and stir fry for about 2-3 minutes or slightly longer. They should still be crunchy but doesn't taste 'green' anymore. Add the grated coconut and stir fry for another 2 minutes","Add the chicken meat and blanched mung bean sprouts followed by seasonings. Stir to mix everything. Turn off the heat","Garnish with bawang goreng and give it a final stir to mix everything. Have a taste. Add more salt if necessary."], cooking_time: "60 mins", servings: 4, cuisine: "Balinese")
tum = Recipe.create(name:"Tum Ayam",image:"https://whattocooktoday.com/wp-content/uploads/2021/09/tum-ayam-18.jpg",description: "These little packets of spiced meat steamed or baked in banana leaves are one of the Balinese cuisine’s real treats. ‘Tum’ can contain any kind of meat and is usually served with rice and vegetables.",instruction:["Clean the banana leaves by rinsing with water. You can soften the leaves by soaking in warm water and then wipe them dry or by holding the leave on top of the fire on the stove to let the heat soften the leaves too. Cut into about 6 pieces of 30 x 30 cm","Heat up a wok or skillet. You don't need to add anymore oil as there's already oil in the spice paste you prepare earlier. Stir fry the spice paste until fragrant over medium heat, about 10 minutes. Have a taste and adjust seasonings to your preference. Remove from the heat and let it cools down a little bit before mixing it with the chicken","You can finely mince the chicken into fine pieces or cut them into thin slices. Alternatively, you can also use ground chicken meat","Divide the chicken mixture into roughly six equal portions. Put one portion on the banana leaves. Top with one fresh bay leaves or 2 dried bay leaves, and few strips of cayenne peppers and wrap it up and secure with a toothpick","Bring the water in the steamer to a boil. Put the packs inside the steamer and steam over medium heat for about 30 minutes or until the chicken is cooked through. You can take one pack out to check for doneness. Serve warm. Remove the bay leaves before eating"], cooking_time: "40 mins", servings: 6, cuisine:" Balinese")
coconut_Pancakes = Recipe.create(name:"Dadar Gulung",image:"https://www.wandercooks.com/wp-content/uploads/2020/08/dadar-gulung-indonesian-coconut-pancake-3.jpg",description: "This traditional dessert is similar to a pancake, but Balinese style. Dadar Gulung is made from rice flour and coconut milk and served with grated coconut and a little sugar on top. Dadar Gulung is usually green, thanks to the addition of the Pandan leaf.",instruction:["In a medium saucepan, place shredded coconut, palm sugar, 1/2 cup water and knotted pandan leaves. Cook filling over low to medium heat. Keep mixing, until all the palm sugar has melted and the coconut turns a beautiful golden brown. This should take around 5 – 10 minutes. Transfer to a bowl to cool slightly.","Grab a large mixing bowl and add your flour, coconut milk, 1/2 cup water, pandan paste, egg and pinch of salt. Whip it together with a whisk, until the batter is quite thin like French crepes","Add a dash of vegetable oil to a medium saucepan on medium-high heat. Wipe it around using a paper towel to coat the whole surface and set aside on a plate to re-oil for the next pancake.","Ladle in approximately 1/3 cup of pancake mix to the pan. Pick the pan up and swirl the mixture in a circular motion to thin it out and coat the bottom of the pan. Allow it to cook slowly on one side. Look for the pancake to turn a slightly darker shade of green all over – then you know it's ready. Give it a shake or two in the pan to make sure it's not stuck, before sliding it onto a plate ready to roll!","Add a few spoonfuls of the coconut filling near the bottom of the pancake. Now it's time to fold! Start with the edge closest to you, lifting it up and over the coconut filling. Next, fold in each side, making sure they’re straight, before rolling the pancake up to the top of the plate.","Serve up straight away with ice-cream, cream and strawberries – or just eat them by themselves."], cooking_time: "25 mins", servings: 10, cuisine: "Balinese,Indonesian")
whiteBait = Recipe.create(name:"WhiteBait Fritters",image:"https://padcook.com/wp-content/uploads/2020/01/c3.jpg",description: "Whitebait fritters are tiny freshwater fish in a batter. Fish is a huge part of the New Zealand diet, mainly because so many Kiwis enjoy going out on fishing trips.", instruction:["Drain your whitebait in a colander. Set aside.","In another bowl, sieve the flour. Make a well and add the beaten eggs with a dash of water, then mix into a smooth, thick batter.","Now gently fold in the whitebait, sliced spring onions and lemon juice (or lemon pepper). Season the mixture with salt and pepper.","Melt butter in a good quality, heavy pan and place a large spoonful of the fritter mixture in the pan. Shape into round fritters and cook until the egg is set or until golden on one side (use egg-flip to peek under). You do not need to wait for the fish to go white. Then gently flip over as you would an omelette and cook the other side for 20 seconds."], cooking_time: "10 mins", servings: 4, cuisine: "New Zealand")
pavlova = Recipe.create(name:"New Zealand Pavlova",image:"https://www.thespruceeats.com/thmb/XgnU04MihUFnAW-JDtV8fzL82cM=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-489765636-5a8c47a38023b900379628b5.jpg",description: "Pavlova is a traditional dessert in New Zealand, and Australia claims it as well. It has a crisp outside and melt-in-your-mouth meringue base that can be filled with any kind of fresh berries or kiwi fruit you like, and then topped with whipped cream.", instruction:["Preheat oven to 400 F. Line a shallow jelly roll pan with parchment paper.","Sprinkle cream of tartar over egg whites and beat until stiff. Whisk together sugar and cornstarch. Add the mixture to the egg whites a tablespoon at a time while beating on medium speed until all is combined. The meringue should be shiny, white, and stiff. Fold in vanilla extract.","Reduce oven heat to 200 F. Mound the meringue on the pan in a round shape about 6 inches in diameter. Bake for 1 hour. Turn off oven, leaving meringue in oven until it is cold, or overnight.","Arrange fruit over the base of the pavlova meringue, top with whipped cream and sprinkle with chips, crushed or small candies and/or additional fruit.","Use a serrated knife to gently saw slices. Store leftovers in a covered container."],cooking_time:"60 mins",servings: 6, cuisine:"New Zealand")

#Ingredients

char_sui_pork = Ingredient.create(name:"Char sui pork")
portuguese_sausage = Ingredient.create(name:"Portuguese sausage")
bacon = Ingredient.create(name:"bacon")
shrimp = Ingredient.create(name:"shrimp")
onion = Ingredient.create(name:"Onion")
eggs = Ingredient.create(name:"eggs")
garlic = Ingredient.create(name:"garlic cloves")
cookinhg_Oil = Ingredient.create(name:"cooking oil")
white_Rice = Ingredient.create(name:"white rice")
ginger_Powder = Ingredient.create(name:"ginger powder")
green_Onion = Ingredient.create(name:"green onion")
soy_Sauce = Ingredient.create(name:"soy sauce")
cheese = Ingredient.create(name:"cheese")
mahi = Ingredient.create(name:"Mahi Mahi")
lime_jucie = Ingredient.create(name:"lime juice")
coconut_milk= Ingredient.create(name:"coconut milk")
tomatoes = Ingredient.create(name:"tomatoes")
green_pepper = Ingredient.create(name:"green pepper")
red_onion = Ingredient.create(name:"red onion")
english_Cucumber = Ingredient.create(name:"English Cucumber")
parsley = Ingredient.create(name:"parsely")
jalapeno = Ingredient.create(name:"jalapeno")
kosher_salt = Ingredient.create(name:"Kosher salt")
black_pepper=Ingredient.create(name:"black pepper")
coconut = Ingredient.create(name:"coconut")
butter_lettuce = Ingredient.create(name:"Butter Lettuce")
plain_flour = Ingredient.create(name:"plain flour")
baking_powder = Ingredient.create(name:"baking powder")
baking_soda = Ingredient.create(name:"baking soda")
sugar = Ingredient.create(name:"sugar")
coconut_cream = Ingredient.create(name:"coconut cream")
nutmeg = Ingredient.create(name:"nutmeg")
cinnamon = Ingredient.create(name:"cinnamon")
ground_clove= Ingredient.create(name:"ground clove")
mochiko = Ingredient.create(name:"mochiko flour")
cornstarch = Ingredient.create(name:"cornstarch")
chicken_thigh = Ingredient.create(name:"chicken thigh")
chicken_breast = Ingredient.create(name:"chicken breast")
seasame_seed = Ingredient.create(name:"sesame seed")
sweet_potato = Ingredient.create(name:"sweet potato")
vanilla = Ingredient.create(name:"vanilla")
water = Ingredient.create(name:"water")
banana_leaves = Ingredient.create(name:"banana leaves")
honey = Ingredient.create(name:"honey")
black_PineappleI = Ingredient.create(name:"black pineapple")
dark_rum = Ingredient.create(name:"dark rum")
green_bean = Ingredient.create(name:"green bean")
mung_bean_sprouts = Ingredient.create(name:"mung bean sprout")
thai_chill = Ingredient.create(name:"thai chilli")
shrimp_paste = Ingredient.create(name:"shrimp paste")
shallots= Ingredient.create(name:"shallots")
coriander_seeds = Ingredient.create(name:"coriander seeds")
coconut_sugar = Ingredient.create(name:"coconut sugar")
bay_leaf = Ingredient.create(name:"bay leaf")
bawang_goreng = Ingredient.create(name:"bawang gorreng")
palm_sugar = Ingredient.create(name:"palm sugar")
pandan_leaves = Ingredient.create(name:"pandan leaves")
pandan_flavouring = Ingredient.create(name:"pandan flavouring")
vegetable_oil = Ingredient.create(name:"vegetable oil")
whitebaitI = Ingredient.create(name:"whitebait")
self_raising_flour = Ingredient.create(name:"self rasing flour")
spring_onion = Ingredient.create(name:"spring onion")
butter = Ingredient.create(name:"butter")
chives = Ingredient.create(name:"chives")
cress = Ingredient.create(name:"cress")
rocket = Ingredient.create(name:"rocket")
cream_of_tartar = Ingredient.create(name:"cream of tartar")
kiwi_peaches_berries = Ingredient.create(name:"kiwi,peaches,berries")
whipped_cream = Ingredient.create(name:"whipped cream")
chocolate_chips = Ingredient.create(name:"chocolate chips")
candies = Ingredient.create(name:"candies")
fruit_slices = Ingredient.create(name:"fruit slices")
cayenne_peppers = Ingredient.create(name:"cayenne peppers")
turmeric = Ingredient.create(name:"turmeric powder")
galangal = Ingredient.create(name:"galangal powder")
ginger = Ingredient.create(name:"ginger")
kencur = Ingredient.create(name:"kencur powder")
lemongrass = Ingredient.create(name:"lemongrass")
kaffir_lime_leaves = Ingredient.create(name:"kaffir lime leaves")
macadamia_nuts = Ingredient.create(name:"macadamia nuts")
coriander_power = Ingredient.create(name:"coriander powder")
white_pepper = Ingredient.create(name:"white pepper")
okra = Ingredient.create(name:"okra")
carrot = Ingredient.create(name:"carrot")
leek = Ingredient.create(name:"leek")
red_pepper = Ingredient.create(name:"red pepper")
cilantro = Ingredient.create(name:"cilantro")
salt = Ingredient.create(name:"salt")
garlic_paste = Ingredient.create(name:"garlic paste")
lime = Ingredient.create(name:"lime")
sambal_oelek = Ingredient.create(name:"sambal oelek")
cornmeal = Ingredient.create(name:"cornmeal")
spinach = Ingredient.create(name:"spinach")





#Recipe_Ingredients

RecipeIngredient.create(amount:"5", unit:"slices of", ingredient: bacon, state:"chopped, diced", recipe: hawaiian_Island_Fried_Rice)
RecipeIngredient.create(amount:"1", unit:"lbs", ingredient:shrimp,recipe:hawaiian_Island_Fried_Rice)
RecipeIngredient.create(amount:"5", unit:"large", state:"minced,finely chopped",ingredient:garlic,recipe:hawaiian_Island_Fried_Rice)
RecipeIngredient.create(amount:"3", unit:"whole", ingredient:eggs, state:"lightly beaten",recipe:hawaiian_Island_Fried_Rice)
RecipeIngredient.create(amount:"5", unit:"oz", ingredient:portuguese_sausage, recipe:hawaiian_Island_Fried_Rice)
RecipeIngredient.create(amount:"1", state:"diced", ingredient:onion, recipe:hawaiian_Island_Fried_Rice)
RecipeIngredient.create(amount:"2", unit:"cup", ingredient:char_sui_pork, recipe:hawaiian_Island_Fried_Rice)
RecipeIngredient.create(ingredient:cookinhg_Oil, recipe:hawaiian_Island_Fried_Rice)


RecipeIngredient.create(amount: "1/4", unit:"cup", ingredient:mochiko, recipe: mochiko_Chicken)
RecipeIngredient.create(amount: "1/4", unit:"cup", ingredient:cornstarch, recipe:mochiko_Chicken)
RecipeIngredient.create(amount: "1/4", unit:"cup", ingredient:sugar, recipe:mochiko_Chicken)
RecipeIngredient.create(amount:"5", unit:"tsp", ingredient:soy_Sauce, recipe:mochiko_Chicken)
RecipeIngredient.create(amount:"2", unit:"whole", ingredient:eggs, recipe:mochiko_Chicken)
RecipeIngredient.create(amount:"1/4", unit:"cup", state:"finely chopped", ingredient:green_Onion, recipe:mochiko_Chicken)
RecipeIngredient.create(amount: "2", unit:"lbs", state:"boneless", ingredient:chicken_thigh, recipe:mochiko_Chicken,)
RecipeIngredient.create(amount: "1", unit:"tbsp", ingredient:seasame_seed, recipe:mochiko_Chicken,)
RecipeIngredient.create(ingredient:cookinhg_Oil, recipe:mochiko_Chicken)


RecipeIngredient.create(amount:"1/2", unit:"cup", ingredient:water, recipe:haupia)
RecipeIngredient.create(amount:"5", unit:"tbsp", ingredient:cornstarch, recipe:haupia)
RecipeIngredient.create(amount:"1", unit:"(13 oz) can",  state:"unsweetened",ingredient: coconut_milk, recipe: haupia,)
RecipeIngredient.create(amount:"1/4", unit:"cup", ingredient:sugar, recipe:haupia)

RecipeIngredient.create(amount:"12", unit:"oz", ingredient:mahi, recipe:kokoda)
RecipeIngredient.create(amount:"3/4,", unit:"cup", ingredient:lime_jucie, recipe:kokoda)
RecipeIngredient.create(amount:"3/4", unit:"cup", ingredient:coconut_milk, recipe:kokoda)
RecipeIngredient.create(amount:"2", state:"finely chopped", ingredient:tomatoes, recipe:kokoda)
RecipeIngredient.create(amount:"1", state:"finely chopped",ingredient:green_pepper, recipe:kokoda)
RecipeIngredient.create(amount:"1/3", unit:"cup", state:"finely diced", ingredient:english_Cucumber, recipe:kokoda,)
RecipeIngredient.create(amount:"1/3", unit:"cup",  state: "chopped",ingredient:parsley, recipe:kokoda,)
RecipeIngredient.create(amount:"1/3", unit:"cup",state:"finely chopped",ingredient:red_onion, recipe:kokoda)
RecipeIngredient.create(amount:"1", state:"finely diced", ingredient: jalapeno, recipe: kokoda)
RecipeIngredient.create(ingredient:black_pepper, recipe:kokoda,)
RecipeIngredient.create(ingredient:coconut, recipe:kokoda)
RecipeIngredient.create(ingredient:butter_lettuce, recipe:kokoda)

RecipeIngredient.create(amount:"10", unit:"oz",ingredient:spinach, state:"frozen chopped", recipe:rourou)
RecipeIngredient.create(amount:"14", unit:"oz", ingredient:coconut_milk, recipe:rourou)
RecipeIngredient.create(amount:"2",unit:"cups", ingredient:water, recipe:rourou)
RecipeIngredient.create(amount:"1/2", unit:"cups", ingredient:onion, recipe:rourou)
RecipeIngredient.create(amount:"3", ingredient:thai_chill, recipe:rourou)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:salt, recipe:rourou)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:garlic_paste, recipe:rourou)
RecipeIngredient.create(amount:"1/2", ingredient:lime, recipe:rourou)


RecipeIngredient.create(amount:"3", unit:"cups", ingredient:plain_flour, recipe:purini)
RecipeIngredient.create(amount:"4", unit:"tsp", ingredient:baking_powder, recipe:purini)
RecipeIngredient.create(amount:"2", unit:"tsp", ingredient:baking_soda, recipe:purini)
RecipeIngredient.create(amount:"2", unit:"cup", ingredient:sugar, recipe:purini)
RecipeIngredient.create(amount:"1", unit:"tin", ingredient:coconut_cream, recipe:purini)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:nutmeg, recipe:purini)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:cinnamon, recipe:purini)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:ground_clove, recipe:purini)

RecipeIngredient.create(amount:"8", ingredient:banana_leaves, recipe:duncana)
RecipeIngredient.create(amount:"1", state:"grated", ingredient:coconut, recipe:duncana)
RecipeIngredient.create(amount:"3", unit:"lbs", state:"grated", ingredient:sweet_potato, recipe:duncana)
RecipeIngredient.create(amount:"2", unit:"cups", ingredient:plain_flour, recipe:duncana)
RecipeIngredient.create(amount:"1/2", unit:"cup", ingredient:sugar, recipe:duncana)
RecipeIngredient.create(amount:"1/2", unit:"cup", ingredient:water, recipe:duncana)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:vanilla, recipe:duncana)
RecipeIngredient.create(amount:"1/2", unit:"tsp", ingredient:cinnamon, recipe:duncana)
RecipeIngredient.create(amount:"1/2", unit:"tsp", ingredient:salt, recipe:duncana)
RecipeIngredient.create(amount:"1/4", unit:"tsp", ingredient:nutmeg, recipe:duncana)

RecipeIngredient.create(amount:"1", state:"ripe", ingredient:black_PineappleI, recipe:black_Pineapple)
RecipeIngredient.create(amount:"1/4", unit:"cup", ingredient:honey, recipe:black_Pineapple)
RecipeIngredient.create(amount:"1", unit:"shot", ingredient:dark_rum, recipe:black_Pineapple)

RecipeIngredient.create(amount:"1", unit:"large", state:"lightly beaten", ingredient:eggs, recipe:tum)
RecipeIngredient.create(amount:"5", ingredient:shallots, recipe:tum)
RecipeIngredient.create(amount:"5", ingredient:garlic, recipe:tum)
RecipeIngredient.create(amount:"3", ingredient:cayenne_peppers, recipe:tum)
RecipeIngredient.create(amount:"2", unit:"tsp", ingredient:turmeric, recipe:tum)
RecipeIngredient.create(amount:"2", unit:"tsp", ingredient:galangal, recipe:tum)
RecipeIngredient.create(amount:"2", unit:"tsp", ingredient:ginger, recipe:tum)
RecipeIngredient.create(amount:"2", unit:"tsp", ingredient:kencur, recipe:tum)
RecipeIngredient.create(amount:"2", unit:"stalks", ingredient:lemongrass, recipe:tum)
RecipeIngredient.create(amount:"4", ingredient:macadamia_nuts, recipe:tum)
RecipeIngredient.create(amount:"2", unit:"tsp", ingredient:coriander_power, recipe:tum)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:shrimp_paste, recipe:tum)
RecipeIngredient.create(amount:"2", unit:"tbsp", ingredient:palm_sugar, recipe:tum)
RecipeIngredient.create(amount:"3", unit:"tbsp", ingredient:cookinhg_Oil, recipe:tum)
RecipeIngredient.create(amount:"1/4", unit:"tsp", state:"ground", ingredient:white_pepper, recipe:tum)
RecipeIngredient.create(amount:"6", state:"fresh", ingredient:bay_leaf, recipe:tum)
RecipeIngredient.create(amount:"1", state:"cut into strips", ingredient:cayenne_peppers, recipe:tum)
RecipeIngredient.create(state:"for wrapping", ingredient:banana_leaves, recipe:tum)

RecipeIngredient.create(amount:"2", unit:"cups", state:"shredded", ingredient:coconut, recipe:coconut_Pancakes)
RecipeIngredient.create(amount:"1", unit:"cup" ,state:"grated", ingredient:palm_sugar, recipe:coconut_Pancakes)
RecipeIngredient.create(amount:"1", unit:"cup", ingredient:water, recipe:coconut_Pancakes)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:pandan_flavouring, recipe:coconut_Pancakes)
RecipeIngredient.create(amount:"1", unit:"cup", ingredient:plain_flour, recipe:coconut_Pancakes)
RecipeIngredient.create(amount:"1", ingredient:eggs,recipe:coconut_Pancakes)
RecipeIngredient.create(amount:"1/2", unit:"tsp", ingredient:salt, recipe:coconut_Pancakes)
RecipeIngredient.create(amount:"2", unit:"cups", ingredient:coconut_milk, recipe:coconut_Pancakes)
RecipeIngredient.create(ingredient:cookinhg_Oil, recipe:coconut_Pancakes)


RecipeIngredient.create(amount:"9", unit:"oz", ingredient:whitebaitI, recipe:whiteBait)
RecipeIngredient.create(amount:"1/2", unit:"cup", ingredient:self_raising_flour, recipe:whiteBait)
RecipeIngredient.create(amount:"2", state:"lightly beaten", ingredient:eggs, recipe:whiteBait)
RecipeIngredient.create(amount:"1", ingredient:lime_jucie, recipe:whiteBait)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:butter, recipe:whiteBait)
RecipeIngredient.create(amount:"1", state:"slice very thinly", ingredient:spring_onion, recipe:whiteBait)
RecipeIngredient.create(amount:"2", unit:"tbsp", ingredient:water, recipe:whiteBait)


RecipeIngredient.create(amount:"4", unit:"large", ingredient:eggs, recipe:pavlova)
RecipeIngredient.create(amount:"1/8", unit:"tsp", ingredient: cream_of_tartar, recipe:pavlova)
RecipeIngredient.create(amount:"1", unit:"cup", state:"superfine", ingredient:sugar, recipe:pavlova)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:cornstarch, recipe:pavlova)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:vanilla, recipe:pavlova)
RecipeIngredient.create(amount:"1 1/2", unit:"cups", ingredient:whipped_cream, recipe:pavlova)
RecipeIngredient.create(amount:"1/4", unit:"cup", ingredient:chocolate_chips, recipe:pavlova)
RecipeIngredient.create(state:"crushed", ingredient:candies, recipe:pavlova)
RecipeIngredient.create(amount:"1", unit:"cup", state:"sliced", ingredient:kiwi_peaches_berries,recipe:pavlova)
RecipeIngredient.create(ingredient:fruit_slices, recipe:pavlova)

RecipeIngredient.create(amount:"10", unit:"oz", ingredient:chicken_thigh, recipe:lawar)
RecipeIngredient.create(amount:"3.5", unit:"oz", ingredient:green_bean, recipe:lawar)
RecipeIngredient.create(amount:"3.5", unit:"oz", ingredient:mung_bean_sprouts, recipe:lawar)
RecipeIngredient.create(amount:"5", unit:"oz", state:"grated", ingredient:coconut, recipe:lawar)
RecipeIngredient.create(amount:"2", unit:"tbsp", ingredient:cookinhg_Oil, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:sambal_oelek,recipe:lawar)
RecipeIngredient.create(amount:"2", ingredient:thai_chill, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:shrimp_paste, recipe:lawar)
RecipeIngredient.create(amount:"4", ingredient:garlic, recipe:lawar)
RecipeIngredient.create(amount:"5", ingredient:shallots, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:coriander_seeds, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:galangal, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"tsp", ingredient:kencur, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:coconut_sugar, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"tbsp", ingredient:lime_jucie, recipe:lawar)
RecipeIngredient.create(amount:"1/4", unit:"tsp", state:"ground", ingredient:black_pepper, recipe:lawar)
RecipeIngredient.create(amount:"1", ingredient:bay_leaf, recipe:lawar)
RecipeIngredient.create(amount:"1", unit:"oz", ingredient:bawang_goreng, recipe:lawar)

RecipeIngredient.create(amount:"1/2", unit:"cup", ingredient:okra, recipe:fungi)
RecipeIngredient.create(amount:"1", unit:"cup", ingredient:cornmeal, recipe:fungi)
RecipeIngredient.create(amount:"1/4", unit:"cup", state:"chilled", ingredient:butter,recipe:fungi)

puts "✅ Done seeding!"
